# Generated by Django 6.0.3 on 2026-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='average_pace',
            field=models.CharField(blank=True, help_text='Ej: 01:45/100m', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='feeling',
            field=models.IntegerField(blank=True, help_text='Sensación/RPE de 1 al 10', null=True),
        ),
    ]
