# Generated by Django 6.0.3 on 2026-04-07 10:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


SPORT_TYPE_MAP = {
    'Swim': 'swim',
    'Bike': 'bike',
    'Run': 'run',
    'Other': 'other',
}


def migrate_workouts_to_activities(apps, schema_editor):
    """Migra datos de Workout a Activity."""
    Workout = apps.get_model('api', 'Workout')
    Activity = apps.get_model('api', 'Activity')

    for workout in Workout.objects.all():
        Activity.objects.create(
            user=workout.user,
            source='manual',
            sport_type=SPORT_TYPE_MAP.get(workout.sport_type, 'other'),
            name=f"{workout.sport_type} on {workout.date}",
            description=workout.notes or '',
            start_time=django.utils.timezone.make_aware(
                django.utils.timezone.datetime.combine(
                    workout.date,
                    django.utils.timezone.datetime.min.time()
                )
            ) if workout.date else django.utils.timezone.now(),
            elapsed_time=workout.duration,
            moving_time=workout.duration,
            distance=workout.distance,
            feeling=workout.feeling,
            completed=workout.completed,
            plan=workout.plan,
            sport_specific_data={},
        )


def reverse_migration(apps, schema_editor):
    """No podemos revertir perfectamente, pero al menos no fallamos."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workout_average_pace_workout_feeling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Primero: Modificar Race y TrainingPlan
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='trainingplan',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='race',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia total en metros', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='race',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='race',
            name='result_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='result_position_age_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='result_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='sport_type',
            field=models.CharField(choices=[('swim', 'Natación'), ('bike', 'Ciclismo'), ('run', 'Carrera'), ('triathlon_sprint', 'Triatlón Sprint'), ('triathlon_olympic', 'Triatlón Olímpico'), ('triathlon_half', 'Medio Ironman (70.3)'), ('triathlon_full', 'Ironman'), ('duathlon', 'Duatlón'), ('other', 'Otro')], default='triathlon_olympic', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='target_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='goal',
            field=models.CharField(blank=True, help_text='Ej: Ironman Barcelona 2026', max_length=200),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        # 2. Crear Activity (antes de borrar Workout)
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='ID externo de Suunto/Garmin para evitar duplicados', max_length=255, null=True, unique=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('suunto', 'Suunto'), ('garmin', 'Garmin'), ('fit_import', 'Importación FIT')], default='manual', max_length=20)),
                ('sport_type', models.CharField(choices=[('swim', 'Natación'), ('bike', 'Ciclismo'), ('run', 'Carrera'), ('transition', 'Transición'), ('multisport', 'Multideporte'), ('strength', 'Fuerza'), ('other', 'Otro')], max_length=20)),
                ('sub_sport', models.CharField(blank=True, choices=[('pool', 'Piscina'), ('open_water', 'Aguas abiertas'), ('road', 'Carretera'), ('mtb', 'Mountain Bike'), ('gravel', 'Gravel'), ('indoor_bike', 'Rodillo / Indoor'), ('road_run', 'Carrera en carretera'), ('trail', 'Trail'), ('track', 'Pista'), ('treadmill', 'Cinta de correr'), ('triathlon', 'Triatlón'), ('duathlon', 'Duatlón'), ('other', 'Otro')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('elapsed_time', models.DurationField(blank=True, help_text='Tiempo total incluyendo pausas', null=True)),
                ('moving_time', models.DurationField(blank=True, help_text='Tiempo solo en movimiento', null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distancia en metros', max_digits=10, null=True)),
                ('total_ascent', models.DecimalField(blank=True, decimal_places=2, help_text='Desnivel positivo en metros', max_digits=8, null=True)),
                ('total_descent', models.DecimalField(blank=True, decimal_places=2, help_text='Desnivel negativo en metros', max_digits=8, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, help_text='FC media (bpm)', null=True)),
                ('max_heart_rate', models.IntegerField(blank=True, help_text='FC máxima (bpm)', null=True)),
                ('min_heart_rate', models.IntegerField(blank=True, help_text='FC mínima (bpm)', null=True)),
                ('avg_speed', models.DecimalField(blank=True, decimal_places=4, help_text='Velocidad media en m/s', max_digits=8, null=True)),
                ('max_speed', models.DecimalField(blank=True, decimal_places=4, help_text='Velocidad máxima en m/s', max_digits=8, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('feeling', models.IntegerField(blank=True, help_text='RPE subjetivo de 1 a 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('training_effect_aerobic', models.DecimalField(blank=True, decimal_places=1, help_text='Training Effect aeróbico (0.0 - 5.0)', max_digits=3, null=True)),
                ('training_effect_anaerobic', models.DecimalField(blank=True, decimal_places=1, help_text='Training Effect anaeróbico (0.0 - 5.0)', max_digits=3, null=True)),
                ('sport_specific_data', models.JSONField(blank=True, default=dict, help_text='Datos específicos: swim(strokes, swolf), bike(power, NP), run(cadence, GCT)')),
                ('raw_fit_file', models.FileField(blank=True, help_text='Archivo FIT original importado', null=True, upload_to='fit_files/%Y/%m/')),
                ('completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.trainingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-start_time'],
            },
        ),

        # 3. MIGRAR DATOS: Workout -> Activity
        migrations.RunPython(migrate_workouts_to_activities, reverse_migration),

        # 4. Añadir FK race -> activity
        migrations.AddField(
            model_name='race',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race', to='api.activity'),
        ),

        # 5. Crear Gear
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gear_type', models.CharField(choices=[('shoes', 'Zapatillas'), ('bike', 'Bicicleta'), ('wetsuit', 'Neopreno'), ('goggles', 'Gafas de natación'), ('helmet', 'Casco'), ('other', 'Otro')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('distance_logged', models.DecimalField(decimal_places=2, default=0, help_text='Distancia acumulada en metros', max_digits=10)),
                ('max_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Vida útil estimada en metros', max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('purchased_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='gear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.gear'),
        ),

        # 6. Crear HeartRateZone, Lap, ProviderConnection
        migrations.CreateModel(
            name='HeartRateZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.IntegerField(help_text='Número de zona (1-5 o 1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('zone_name', models.CharField(blank=True, help_text='Ej: Z1 Recovery, Z2 Endurance', max_length=50)),
                ('min_hr', models.IntegerField(help_text='FC mínima de la zona (bpm)')),
                ('max_hr', models.IntegerField(help_text='FC máxima de la zona (bpm)')),
                ('time_in_zone', models.DurationField(help_text='Tiempo en esta zona')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_zones', to='api.activity')),
            ],
            options={
                'ordering': ['activity', 'zone_number'],
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_index', models.IntegerField(help_text='Orden de la vuelta (empieza en 0)')),
                ('sport_type', models.CharField(blank=True, choices=[('swim', 'Natación'), ('bike', 'Ciclismo'), ('run', 'Carrera'), ('transition', 'Transición'), ('multisport', 'Multideporte'), ('strength', 'Fuerza'), ('other', 'Otro')], help_text='Deporte de esta vuelta (importante en multisport)', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('elapsed_time', models.DurationField(blank=True, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distancia en metros', max_digits=10, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('max_heart_rate', models.IntegerField(blank=True, null=True)),
                ('avg_speed', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('max_speed', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('avg_cadence', models.IntegerField(blank=True, null=True)),
                ('avg_power', models.IntegerField(blank=True, null=True)),
                ('total_ascent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_descent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('lap_trigger', models.CharField(blank=True, choices=[('manual', 'Manual'), ('distance', 'Distancia'), ('time', 'Tiempo'), ('position_start', 'Posición inicio'), ('session_end', 'Fin de sesión'), ('auto', 'Automático')], max_length=20)),
                ('sport_specific_data', models.JSONField(blank=True, default=dict, help_text='Datos específicos del lap: swim(stroke_count, swolf), bike(NP), etc.')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='api.activity')),
            ],
            options={
                'ordering': ['activity', 'lap_index'],
            },
        ),
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('suunto', 'Suunto'), ('garmin', 'Garmin')], max_length=20)),
                ('access_token', models.TextField(help_text='Token de acceso OAuth (encriptar en producción)')),
                ('refresh_token', models.TextField(blank=True, help_text='Refresh token OAuth')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_scope', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_errors', models.IntegerField(default=0, help_text='Contador de errores consecutivos de sync')),
                ('provider_user_id', models.CharField(blank=True, help_text='ID del usuario en el proveedor (Suunto/Garmin)', max_length=255)),
                ('provider_metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del proveedor (nombre, email, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider'],
            },
        ),

        # 7. Ahora sí borrar Workout (ya migrados los datos)
        migrations.DeleteModel(
            name='Workout',
        ),

        # 8. Índices y constraints
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'sport_type'], name='api_activit_user_id_c06ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'start_time'], name='api_activit_user_id_22e1c6_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['external_id'], name='api_activit_externa_479843_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['source'], name='api_activit_source_2909b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='heartratezone',
            unique_together={('activity', 'zone_number')},
        ),
        migrations.AlterUniqueTogether(
            name='lap',
            unique_together={('activity', 'lap_index')},
        ),
        migrations.AlterUniqueTogether(
            name='providerconnection',
            unique_together={('user', 'provider')},
        ),
    ]
