# Generated by Django 6.0.5 on 2026-05-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_race_options_alter_trainingplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='gear',
        ),
        migrations.AddField(
            model_name='activity',
            name='gear',
            field=models.ManyToManyField(blank=True, related_name='activities', to='api.gear'),
        ),
    ]
