# Generated by Django 6.0.5 on 2026-05-25 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_activity_gear_activity_gear'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, help_text='URL de la foto de perfil', max_length=500)),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('elite', 'Élite')], default='intermediate', max_length=20)),
                ('main_goal', models.CharField(blank=True, help_text='Ej: Terminar mi primer Ironman', max_length=200)),
                ('triathlon_modality', models.CharField(choices=[('sprint', 'Sprint'), ('olympic', 'Olímpico'), ('half', 'Half / 70.3'), ('full', 'Full / Ironman'), ('other', 'Otro')], default='olympic', max_length=20)),
                ('weekly_workout_goal', models.IntegerField(default=4, help_text='Objetivo semanal de entrenamientos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
